# Generated by Django 2.2.1 on 2019-05-16 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eignir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullt_nafn', models.CharField(max_length=255)),
                ('kennitala', models.IntegerField()),
                ('heimilisfang', models.CharField(max_length=255)),
                ('borg', models.CharField(max_length=255)),
                ('postnr', models.IntegerField()),
                ('netfang', models.EmailField(max_length=50)),
                ('simi', models.IntegerField()),
                ('mynd', models.CharField(blank=True, max_length=9999)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Land')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leitarsaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eignir.Eign')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
