# Generated by Django 2.2.1 on 2019-05-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notandi',
            new_name='user',
        ),
    ]
