# Generated by Django 2.2.1 on 2019-05-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinhus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinhus',
            name='eign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='er_opid', to='eignir.Eign'),
        ),
    ]
