# Generated by Django 2.2.1 on 2019-05-16 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantanir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heimilisfang', models.CharField(max_length=255)),
                ('baejarfelag', models.CharField(max_length=255)),
                ('postnumer', models.IntegerField()),
                ('verd', models.IntegerField()),
                ('brunabotamat', models.IntegerField()),
                ('fasteignamat', models.IntegerField()),
                ('tegund', models.CharField(max_length=255)),
                ('staerd', models.IntegerField()),
                ('byggingarar', models.DateField()),
                ('fjoldi_herbergja', models.IntegerField()),
                ('fjoldi_badherberga', models.IntegerField()),
                ('fjoldi_svefnherberga', models.IntegerField()),
                ('sett_a_solu', models.DateField()),
                ('nafn_seljanda', models.CharField(max_length=255)),
                ('simi_seljanda', models.IntegerField()),
                ('netfang_seljanda', models.EmailField(max_length=255)),
                ('starfsmenn', models.CharField(max_length=255)),
                ('nafn_kaupanda', models.CharField(max_length=255)),
                ('simi_kaupanda', models.IntegerField()),
                ('netfang_kaupanda', models.EmailField(max_length=255)),
                ('kennitala_kaupanda', models.IntegerField()),
                ('heimilisfang_kaupanda', models.CharField(max_length=255)),
                ('borg_kaupanda', models.CharField(max_length=255)),
                ('land_kaupanda', models.CharField(max_length=255)),
                ('postnr_kaupanda', models.CharField(max_length=255)),
                ('notandanafn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
