# Generated by Django 2.2.1 on 2019-05-15 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eignir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantanir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kortanumer', models.CharField(max_length=19)),
                ('dagsetning_manudur', models.IntegerField()),
                ('dagsetning_ar', models.IntegerField()),
                ('eignir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eignir.Eign')),
                ('notandanafn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
