# Generated by Django 2.2.1 on 2019-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantanir',
            name='dagsetning_kort',
        ),
        migrations.AddField(
            model_name='pantanir',
            name='dagsetning_ar',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pantanir',
            name='dagsetning_manudur',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
