# Generated by Django 2.2.1 on 2019-05-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eignir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eign',
            old_name='Brunabotamat',
            new_name='brunabotamat',
        ),
        migrations.RenameField(
            model_name='eign',
            old_name='Fasteignamat',
            new_name='fasteignamat',
        ),
    ]
