# Generated by Django 2.2.1 on 2019-05-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfsmenn', '0001_initial'),
        ('eignir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('Town_name', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Brunabotamat', models.IntegerField()),
                ('Fasteignamat', models.IntegerField()),
                ('Type', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=999)),
                ('Size', models.FloatField()),
                ('Building_year', models.DateField()),
                ('Number_of_rooms', models.IntegerField()),
                ('Number_of_bathrooms', models.IntegerField()),
                ('Number_of_bedrooms', models.IntegerField()),
                ('put_on_sale', models.DateTimeField()),
                ('Available_now', models.BooleanField()),
                ('Housed_drawing', models.BooleanField()),
                ('private_entrance', models.BooleanField()),
                ('public_entrance', models.BooleanField()),
                ('Sundeck', models.BooleanField()),
                ('Balcony', models.BooleanField()),
                ('Garden', models.BooleanField()),
                ('Laundry_room', models.BooleanField()),
                ('wheelchair_Access', models.BooleanField()),
                ('Elevator', models.BooleanField()),
                ('Garage', models.BooleanField()),
                ('Parking_Space', models.BooleanField()),
                ('Seller_Name', models.CharField(max_length=255)),
                ('Seller_Phone', models.IntegerField()),
                ('Seller_Email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EignImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('Eign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eignir.Eign')),
            ],
        ),
        migrations.CreateModel(
            name='GPSMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField(max_length=(10, 6))),
                ('lng', models.FloatField(max_length=(10, 6))),
            ],
        ),
        migrations.DeleteModel(
            name='Eignir',
        ),
        migrations.AddField(
            model_name='eign',
            name='Marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eignir.GPSMarker'),
        ),
        migrations.AddField(
            model_name='eign',
            name='Starfsmenn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starfsmenn.Starfsmenn'),
        ),
    ]
